Places cards
maxaleks/foursquare-bot pull request #6
Opened 2017-06-27 21:20 UTC by maxaleks

2017-06-28 06:57 UTC, MaksimAbramchuk requested changes

2017-06-28 06:57 UTC, MaximAbramchuck commented on src/bot/controllers/SearchController.js
> +        switch (category) {
Let's move with one to the object an retrieve needed category by key
For example
```
const categoryObject = {
  BREAKFAST: 'breakfast',
  COFFEE: 'coffee show',
  FAST_FOOD: 'fast food',
  ...
}
```

and then retrieve like `categoryObject[category]`

2017-06-28 06:57 UTC, MaximAbramchuck commented on src/bot/controllers/SearchController.js
> +        const categoryId = categories.find(item => item.name === category).externalId;
why not to to this search using db request?

2017-06-28 06:57 UTC, MaximAbramchuck commented on src/bot/controllers/SearchController.js
> +            return new CarouselElement(
What do you think about moving this one to some kind of helper? Let's say you'll need to render places in another controller also. With helper method you can just pass `item` object and receive already built `carousel`.

2017-06-28 06:57 UTC, MaximAbramchuck commented on src/bot/controllers/SearchController.js
> +        return this.sendCategories($, this.i18n('search.somethingElse'));
reusability 👍

2017-06-28 06:57 UTC, MaximAbramchuck commented on src/integrations/foursquare/index.js
> +const axios = require('axios');
Let's move this one to a class Foursquare API, similar to this one for example: https://gist.github.com/MaximAbramchuck/d99dc99b90fdc1d55e4aad060015c314

2017-06-28 06:57 UTC, MaximAbramchuck commented on src/db/BotDatabase.js
> +        const model = this._models.Category;
no need to set a variable, it's used only 1 time

2017-06-28 06:57 UTC, MaximAbramchuck commented on src/db/BotDatabase.js
> +        return model.findAll({});
`{}` is not necessary

2017-06-28 06:57 UTC, MaximAbramchuck commented on src/db/BotDatabase.js
> +            return obj ? obj.update(item) : model.create(item)
There is `findOrCreate` method in Sequelize, I think it does pretty similar thing, take a look. Usually I combine `findOrCreate` and then do `update`

2017-06-28 07:23 UTC, OverVlad commented on src/bot/controllers/SearchController.js
> +        switch (category) {
@MaximAbramchuck constant naming pattern is 
`const MY_OBJECT = {'key': 'value'}; `
In our situation we can name:
`const CATEGORY = {
caffe: 'take a coffe' ,
...
}`

2017-06-28 07:33 UTC, OverVlad commented on src/bot/controllers/SearchController.js
> +            return new CarouselElement(
Maybe we can create serializer and receive data in format: item.imageUrl like this one:
https://github.com/maxaleks/foursquare-bot/blob/development/src/integrations/smooch/WebhookUpdate.js

2017-06-28 09:47 UTC, maxaleks commented on src/integrations/foursquare/index.js
> +const axios = require('axios');
@MaximAbramchuck, what are the advantages of this approach?

2017-06-28 09:57 UTC, MaximAbramchuck commented on src/integrations/foursquare/index.js
> +const axios = require('axios');
@maxaleks because our architecture is built fully on OOP patterns, so we use classes everywhere

2017-06-29 12:13 UTC, MaksimAbramchuk approved these changes

2017-06-29 12:13 UTC, MaximAbramchuck commented on .eslintrc
> +        arrays: "always-multiline",
:+1:

2017-06-29 12:13 UTC, MaximAbramchuck commented on src/bot/controllers/SearchController.js
> +        const CATEGORY = {
`CATEGORIES` will be better I think

2017-06-29 12:13 UTC, MaximAbramchuck commented on src/db/BotDatabase.js
> +        const model = this._models.Category;
no need to set a variable, it's used only 1 time

2017-06-29 12:13 UTC, MaximAbramchuck commented
:shipit:

2017-06-29 17:42 UTC, merged